# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: true

before_install:
  - source travis/before-install.sh

addons:
  apt:
    packages:
      - gcc-4.4
      - g++-4.4
      - clang

r:
  - oldrel
  - release
  - devel

env:
  - CC=gcc-4.4 CXX=g++-4.4
  - CC=gcc     CXX=g++
- CC=clang   CXX=clang++
